#!/usr/bin/env sh

#wrapper for git
#https://wiki.archlinux.org/title/Dotfiles#Tracking_dotfiles_directly_with_Git
#run: 
#>dotc config status.showUntrackedFiles no
#to ignore untracked files

/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
